### ISSUE TITLE
Mission issue

### ISSUE THREAD

**Issue by SuperRenzi** [Waurum-Studio/waurum-issues#11]
### Expected Behavior

Missions Showing

### Actual Behavior

Missions not showing up sometimes

### Reproduction Steps

```markdown
1.Open the missions tab
2.Pray that it is a bug
```

### Concerned Platform(s)

[GMOD]  Pedobear Server

### Version

v4.2

### Console Error

![image](https://user-images.githubusercontent.com/107997958/175113571-95f99ea4-122e-4ac3-a681-793635928a65.png)

### Additional Information

This bug is pretty rare.

**Comment by dotCore-off** [comment]
To fix this one, I'll definitely need more context.

A good test would be to check if, your Daily missions tab errors, you received or not the "You have X active missions, type !challenges." when joining in.

If no, that means that there's an issue w/ binding mission datas to the local player.
Else, I've got no idea where it could come from.

Switching priority to none since it's a really rare bug and can be fixed easily.

**Comment by dotCore-off** [comment]
Fixed :)
